import Details from "@/components/sections/Details";
import Footer from "@/components/sections/Footer";
import Header from "@/components/sections/Header";
import Hero from "@/components/sections/Hero";
import Specifics from "@/components/sections/Specifics";
import Head from "next/head";
import TeamMembers from "@/components/sections/Team";
import Partnerships from "@/components/sections/Partnerships";

export default function Home() {
  return (
    <>
      <Head>
        <title>Water Monster</title>
        <meta name="description" content="Generated by Water Monster" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-4">
        <Header />
        <Hero />
      </div>
      <main className="max-w-7xl mx-auto px-4">
        <Specifics />
        <Details />
        <Partnerships />
        <TeamMembers />
      </main>
      <Footer />
    </>
  );
}
